version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: webChat_container
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: root 

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    ports:
      - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root 
      ME_CONFIG_MONGODB_ADMINPASSWORD: root 
      ME_CONFIG_MONGODB_SERVER: mongodb 
    depends_on:
      - mongodb 

  nestjs-api:
    build:
      context: ./ 
      dockerfile: Dockerfile 
    container_name: nestjs_api_container
    ports:
      - "3000:3000" 
    environment:
      DATABASE_HOST: mongodb 
      DATABASE_PORT: 27017
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    depends_on:
      - mongodb 
volumes:
  mongo-data: 
